"""`spark-lab recipes` -- discovery + conversion of model recipes (ADR 0003).

Read-only, non-disruptive commands over the configured discovery sources:

    recipes search <query>   fan a query out to enabled sources, merge + dedup
    recipes list [source]    enumerate one source (or all)
    recipes show <ref>       resolve <source://ref>, print metadata + native body
    recipes convert <ref>    produce a sparkrun *candidate* recipe (never applied)

Commands know only the ``RecipeSource`` contract + the record type (ADR 0003);
which sources exist comes entirely from ``config.yaml``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

from ..core import config as config_mod
from ..core.discovery import DiscoveryRegistry
from ..core.discovery import convert as cv


def _registry(args) -> DiscoveryRegistry:
    cfg = config_mod.load(args.config)
    disc = cfg.discovery() or {}
    cache = disc.get("cache_dir")
    cache_path = None
    if cache:
        p = Path(str(cache)).expanduser()
        cache_path = p if p.is_absolute() else Path.cwd() / p
    return DiscoveryRegistry(cfg, runtime=getattr(args, "runtime", None), cache_dir=cache_path)


def _print_records(records, errors, as_json: bool):
    if as_json:
        print(json.dumps([r.to_dict() for r in records], indent=2))
    else:
        for r in records:
            print(f"{r.ref}  {r.name or r.reference}")
            print(f"    model={r.model_id}  image={r.image}  tags={','.join(r.tags)}")
    for alias, err in errors:
        print(f"  [{alias}] {err}", file=sys.stderr)


def search(args) -> int:
    reg = _registry(args)
    try:
        records, errors = reg.search(args.query, source=getattr(args, "source", None))
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1
    _print_records(records, errors, getattr(args, "json", False))
    return 0


def list_(args) -> int:
    reg = _registry(args)
    try:
        records, errors = reg.list(source=getattr(args, "source", None))
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1
    _print_records(records, errors, getattr(args, "json", False))
    return 0


def show(args) -> int:
    reg = _registry(args)
    try:
        rec = reg.show(args.reference)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1
    if getattr(args, "json", False):
        print(rec.to_json(with_body=True))
        return 0
    for k in ("source", "reference", "name", "description", "origin", "model_id",
              "serving_framework", "image", "hardware", "tags"):
        print(f"  {k:<16} {getattr(rec, k)}")
    if rec.body:
        print("  -- native body --")
        print(yaml.safe_dump(rec.body, sort_keys=False, allow_unicode=True))
    return 0


def convert(args) -> int:
    reg = _registry(args)
    try:
        rec = reg.show(args.reference)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1

    conv = (reg.config.discovery() or {}).get("convert", {}) or {}
    llm_transport = None
    if conv.get("llm") and conv.get("endpoint"):
        llm_transport = cv.make_llm_transport(
            conv["endpoint"], conv.get("model", "my-spark-model"),
            reg.config.secret(conv.get("key_env")), getattr(args, "runtime", None))

    cand = cv.build_candidate(rec, llm_transport=llm_transport)
    problems = cv.validate_candidate(cand)
    if problems:
        print(f"[ERROR] candidate failed validation: {'; '.join(problems)}", file=sys.stderr)
        return 1

    if getattr(args, "dry_run", False):
        print("[dry-run] candidate recipe (not written, not applied):")
        print(yaml.safe_dump(cand, sort_keys=False, allow_unicode=True))
        return 0

    out = Path(args.out) if args.out else Path("recipes/candidates") / f"{rec.reference}.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# CANDIDATE sparkrun recipe (generated by `spark-lab recipes convert`).\n"
                   "# Review + validate before use. This is never auto-applied.\n"
                   + yaml.safe_dump(cand, sort_keys=False, allow_unicode=True))
    print(f"Wrote candidate recipe -> {out}")
    print(f"  source: {rec.ref}  |  provenance: {cand.get('_candidate_source')}")
    print("  Candidate only: review and validate before use; it is never auto-applied.")
    return 0
